# List of all the board related files.
RTT_C_SOURCES = ARM_SEGGER_RTT/RTT/SEGGER_RTT.c \
		 ARM_SEGGER_RTT/RTT/SEGGER_RTT_printf.c

# Required include directories
RTT_INCLUDES = ARM_SEGGER_RTT/RTT \
		ARM_SEGGER_RTT \
		

EXTRA_C_SOURCES += $(RTT_C_SOURCES)
EXTRA_INCLUDES += $(RTT_INCLUDES)
