#ifndef NH10_SKIP_ASM_RTT_CFG_H
#define NH10_SKIP_ASM_RTT_CFG_H

#define RTT_USER_CFG_ENABLE 1
#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 0
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 1
#define LOG_ENABLE_DEBUG 1
#define LOG_ENABLE_WARN 1
#define LOG_ENABLE_ERROR 1
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 1
#define RTT_FLOAT_USE_MODFF 0
#define RTT_LOG_FLOAT_FAST_PATH 0
#define RTT_WRITE_SKIP_USE_ASM 1
#define RTT_LOG_BUFFER_INDEX 0u
#define RTT_LOG_USE_COLOR 1
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 3
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 3
#define BUFFER_SIZE_UP 1024
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#endif
