#ifndef ARM_SEGGER_RTT_HW_TEST_CONFIG_H
#define ARM_SEGGER_RTT_HW_TEST_CONFIG_H

#ifndef HW_TEST_CASE
#define HW_TEST_CASE 8
#endif
#ifndef HW_TEST_PROFILE
#define HW_TEST_PROFILE 0
#endif
#ifndef HW_TEST_UP_SIZE
#define HW_TEST_UP_SIZE 256
#endif
#ifndef HW08_FLOAT_FAST
#define HW08_FLOAT_FAST 0
#endif
#ifndef HW08_SKIP_ASM
#define HW08_SKIP_ASM 0
#endif

#define RTT_USER_CFG_ENABLE 1

#if HW_TEST_CASE == 3

#define RTT_LOG_ENABLE 1
#if (HW_TEST_PROFILE == 0) || (HW_TEST_PROFILE == 1) || (HW_TEST_PROFILE == 2)
#define LOG_ENABLE_LITE        ((HW_TEST_PROFILE == 2) ? 1 : 0)
#define LOG_ENABLE_TYPED       0
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO        1
#define LOG_ENABLE_DEBUG       1
#define LOG_ENABLE_WARN        1
#define LOG_ENABLE_ERROR       1
#define LOG_ENABLE_PRINT       1
#define LOG_ENABLE_STRING      1
#define LOG_ENABLE_FLOAT       1
#define RTT_LOG_USE_COLOR      ((HW_TEST_PROFILE == 1) ? 0 : 1)
#define RTT_LOG_BUFFER_INDEX   0u
#elif HW_TEST_PROFILE == 3
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 0
#define LOG_ENABLE_STRING 0
#define LOG_ENABLE_FLOAT 0
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#elif HW_TEST_PROFILE == 4
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 0
#define LOG_ENABLE_TYPED_FLOAT 1
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 0
#define LOG_ENABLE_STRING 0
#define LOG_ENABLE_FLOAT 0
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#elif HW_TEST_PROFILE == 5
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 1
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 0
#define LOG_ENABLE_STRING 0
#define LOG_ENABLE_FLOAT 0
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#elif HW_TEST_PROFILE == 6
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 1
#define LOG_ENABLE_INFO 1
#define LOG_ENABLE_DEBUG 1
#define LOG_ENABLE_WARN 1
#define LOG_ENABLE_ERROR 1
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 1
#define RTT_LOG_USE_COLOR 1
#define RTT_LOG_BUFFER_INDEX 1u
#else
#error "unsupported HW03 profile"
#endif
#define RTT_FLOAT_USE_MODFF 0
#define RTT_LOG_FLOAT_FAST_PATH 0
#define RTT_WRITE_SKIP_USE_ASM 0
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 3
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 3
#define BUFFER_SIZE_UP 1024
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#elif HW_TEST_CASE == 4

#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 0
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 1
#define LOG_ENABLE_DEBUG 1
#define LOG_ENABLE_WARN 1
#define LOG_ENABLE_ERROR 1
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 1
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#define RTT_FLOAT_USE_MODFF 0
#define RTT_LOG_FLOAT_FAST_PATH 0
#define RTT_WRITE_SKIP_USE_ASM HW_TEST_PROFILE
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 2
#if HW_TEST_MCU_FAMILY == 0
#define BUFFER_SIZE_UP 2048
#else
#define BUFFER_SIZE_UP 4096
#endif
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 128u

#elif HW_TEST_CASE == 5

#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 1
#define LOG_ENABLE_TYPED 0
#define LOG_ENABLE_TYPED_FLOAT 1
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 0
#define LOG_ENABLE_STRING 0
#define LOG_ENABLE_FLOAT 1
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#define RTT_FLOAT_USE_MODFF ((HW_TEST_PROFILE >> 1) & 1)
#define RTT_LOG_FLOAT_FAST_PATH (HW_TEST_PROFILE & 1)
#define RTT_WRITE_SKIP_USE_ASM 0
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 1
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 1
#if HW_TEST_MCU_FAMILY == 0
#define BUFFER_SIZE_UP 2048
#else
#define BUFFER_SIZE_UP 4096
#endif
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 128u

#elif HW_TEST_CASE == 6

#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 1
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 0
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 1u
#define RTT_WRITE_SKIP_USE_ASM 0
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 1
#if HW_TEST_MCU_FAMILY == 0
#define BUFFER_SIZE_UP 1024
#else
#define BUFFER_SIZE_UP 4096
#endif
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#elif HW_TEST_CASE == 7

#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 1
#define LOG_ENABLE_TYPED 0
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 0
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 0u
#define RTT_WRITE_SKIP_USE_ASM 0
#define SEGGER_RTT_MAX_INTERRUPT_PRIORITY 0x20
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 1
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 1
#if HW_TEST_MCU_FAMILY == 0
#define BUFFER_SIZE_UP 2048
#elif HW_TEST_MCU_FAMILY == 1
#define BUFFER_SIZE_UP 8192
#else
#define BUFFER_SIZE_UP 65536
#endif
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#elif HW_TEST_CASE == 8

#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 1
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 0
#define LOG_ENABLE_INFO 0
#define LOG_ENABLE_DEBUG 0
#define LOG_ENABLE_WARN 0
#define LOG_ENABLE_ERROR 0
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 1
#define RTT_LOG_USE_COLOR 0
#define RTT_LOG_BUFFER_INDEX 1u
#define RTT_LOG_FLOAT_FAST_PATH HW08_FLOAT_FAST
#define RTT_WRITE_SKIP_USE_ASM HW08_SKIP_ASM
#if HW_TEST_MCU_FAMILY != 0
#define SEGGER_RTT_MAX_INTERRUPT_PRIORITY 0x20
#endif
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 2
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 1
#if HW_TEST_MCU_FAMILY == 0
#define BUFFER_SIZE_UP 1536
#elif HW_TEST_MCU_FAMILY == 1
#define BUFFER_SIZE_UP 8192
#else
#define BUFFER_SIZE_UP 65536
#endif
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#else

/* HW01 and HW02 need the complete public logging surface. */
#define RTT_LOG_ENABLE 1
#define LOG_ENABLE_LITE 0
#define LOG_ENABLE_TYPED 1
#define LOG_ENABLE_TYPED_FLOAT 1
#define LOG_ENABLE_INFO 1
#define LOG_ENABLE_DEBUG 1
#define LOG_ENABLE_WARN 1
#define LOG_ENABLE_ERROR 1
#define LOG_ENABLE_PRINT 1
#define LOG_ENABLE_STRING 1
#define LOG_ENABLE_FLOAT 1
#define RTT_FLOAT_USE_MODFF 0
#define RTT_LOG_FLOAT_FAST_PATH 0
#define RTT_WRITE_SKIP_USE_ASM 0
#define RTT_LOG_BUFFER_INDEX 0u
#define RTT_LOG_USE_COLOR 1
#define SEGGER_RTT_MAX_NUM_UP_BUFFERS 3
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS 3
#define BUFFER_SIZE_UP 1024
#define BUFFER_SIZE_DOWN 16
#define SEGGER_RTT_PRINTF_BUFFER_SIZE 64u

#endif

#if HW_TEST_MCU_FAMILY == 7
#define SEGGER_RTT_SECTION        ".rtt_cb"
#define SEGGER_RTT_BUFFER_SECTION ".rtt_buffer"
#endif

#endif
